compress

tacos/logs/error*.log {
    rotate 10
    size 100M
    olddir old/error
    missingok
    copytruncate
    delaycompress
}

tacos/logs/build*.log {
    rotate 10
    size 500M
    olddir old/build
    missingok
    delaycompress
}
