server:
    ip-address: 127.0.0.1
    port: FUZZ_PORT
    server-count: 1
    do-ip4: yes
    do-ip6: no
    username: RUN_USER
    zonesdir: "RUN_DIRECTORY/etc/nsd"
    database: "RUN_DIRECTORY/var/db/nsd/nsd.db"
    logfile: "RUN_DIRECTORY/log/nsd.log"
    pidfile: "RUN_DIRECTORY/run/nsd.pid"
    xfrdfile: "RUN_DIRECTORY/var/db/nsd/xfrd.state"
    xfrdir: "RUN_DIRECTORY/var/db/nsd"
    zonelistfile: "RUN_DIRECTORY/var/db/nsd/zone.list"
    identity: "nsd-fuzz"
    version: "NSD fuzz"
    nsid: "6e73642d66757a7a"
    answer-cookie: yes
    cookie-secret: "000102030405060708090a0b0c0d0e0f"
    udp-padding-port: FUZZ_PORT
    verbosity: 2

remote-control:
    control-enable: no

zone:
    name: example.com
    zonefile: example.com.zone
    provide-xfr: 0.0.0.0/0 NOKEY
    provide-xfr: ::0/0 NOKEY

zone:
    name: example.org
    zonefile: example.org.zone
    provide-xfr: 0.0.0.0/0 NOKEY
    provide-xfr: ::0/0 NOKEY

zone:
    name: example
    zonefile: nsec3.example.zone
    provide-xfr: 0.0.0.0/0 NOKEY
    provide-xfr: ::0/0 NOKEY

zone:
    name: "."
    zonefile: root.zone
    provide-xfr: 0.0.0.0/0 NOKEY
    provide-xfr: ::0/0 NOKEY
